name: powerop-ml-deployment
environment: production

services:
  webapp:
    name: powerop-ml-app
    sku: F1 # Free tier
    region: eastus

  ml_workspace:
    name: powerop-ml-workspace
    sku: basic
    region: eastus

  openai:
    name: powerop-openai
    sku: S0
    region: eastus
    deployments:
      - model: gpt-35-turbo
        capacity: 1

monitoring:
  enabled: true
  alerts:
    budget:
      limit: 50 # 50% of student credit
      email: true
