server:
  host: "0.0.0.0"
  port: 8000

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://hvac-dashboard.example.com"

authentication:
  token_expiration: 3600  # seconds
  refresh_token_expiration: 86400  # seconds

alerts:
  threshold_multiplier: 1.5
  min_consecutive_anomalies: 3
  cooldown_period: 300
  alert_levels:
    warning: 1.5
    critical: 2.0
    emergency: 3.0

services:
  weather:
    cache_ttl: 1800
    max_retries: 3
  groq:
    max_tokens: 1024
    temperature: 0.7
    cache_ttl: 3600

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/hvac_system.log"

development_mode: false
