name: Azure FastAPI Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Create deployment package
        run: |
          echo "=== Verifying files before packaging ==="
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

          echo "=== Creating deployment directory ==="
          mkdir -p deploy

          echo "=== Copying files ==="
          # Essential files
          cp -v startup.sh deploy/
          cp -v requirements.txt deploy/
          cp -v gunicorn_config.py deploy/
          cp -v runtime.txt deploy/
          cp -v .deployment deploy/

          echo "=== Copying API directory ==="
          cp -rv api deploy/

          echo "=== Verifying deployment directory ==="
          echo "Deployment directory contents:"
          ls -la deploy/
          echo "API directory contents:"
          ls -la deploy/api/

          echo "=== Creating ZIP archive ==="
          cd deploy
          zip -r ../deploy.zip .
          cd ..

          echo "=== Final package verification ==="
          echo "ZIP file size: $(ls -lh deploy.zip)"
          echo "ZIP contents:"
          unzip -l deploy.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App
        run: |
          # Update Python configuration
          az webapp config set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --linux-fx-version "PYTHON|3.9"

          # Configure app settings including startup command
          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              WEBSITES_PORT=8000 \
              PYTHON_VERSION=3.9 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              WEBSITE_RUN_FROM_PACKAGE=1 \
              STARTUP_COMMAND="gunicorn -c gunicorn_config.py api.main:app"

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: powerop-app
          package: deploy.zip

      - name: Deployment verification
        if: steps.deploy.outcome == 'success'
        run: |
          echo "=== Waiting for deployment to stabilize ==="
          sleep 60  # Increased wait time

          echo "=== Checking web app status ==="
          STATUS=$(az webapp show --name powerop-app --resource-group powerop-ml-rg --query state -o tsv)
          echo "Web app status: $STATUS"

          if [ "$STATUS" != "Running" ]; then
            echo "Web app is not in Running state"
            exit 1
          fi

          echo "=== Testing application health endpoint ==="
          WEBAPP_URL=$(az webapp show --name powerop-app --resource-group powerop-ml-rg --query defaultHostName -o tsv)
          MAX_RETRIES=5
          RETRY_COUNT=0

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://$WEBAPP_URL/health")
            if [ "$HTTP_STATUS" = "200" ]; then
              echo "Health check successful!"
              exit 0
            fi
            echo "Attempt $((RETRY_COUNT+1))/$MAX_RETRIES: Health check returned $HTTP_STATUS"
            RETRY_COUNT=$((RETRY_COUNT+1))
            sleep 30
          done

          echo "Health check failed after $MAX_RETRIES attempts"
          exit 1
