name: Azure FastAPI Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Python Runtime
        run: |
          az webapp config set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --linux-fx-version "PYTHON|3.9"

      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              PYTHON_VERSION=3.9 \
              STARTUP_COMMAND="gunicorn --bind=0.0.0.0 --timeout 600 api.main:app --workers 4"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: powerop-app
          package: .

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          STATUS=$(az webapp show --name powerop-app --resource-group powerop-ml-rg --query state -o tsv)
          echo "Web App Status: $STATUS"

          if [ "$STATUS" != "Running" ]; then
            echo "Checking logs for errors..."
            az webapp log tail --name powerop-app --resource-group powerop-ml-rg
            exit 1
          fi
