name: Azure FastAPI Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Prepare deployment
        run: |
          # Make startup script executable
          chmod +x startup.sh

          # Create deployment package
          zip -r deploy.zip . -x "*.git*"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App
        run: |
          # Configure app settings first
          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              WEBSITES_PORT=8000 \
              PYTHON_VERSION=3.9 \
              WEBSITE_RUN_FROM_PACKAGE=1

          # Update Python configuration
          az webapp config set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --linux-fx-version "PYTHON|3.9" \
            --startup-command "/home/site/wwwroot/startup.sh"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: powerop-app
          package: deploy.zip

      - name: Check deployment
        run: |
          echo "Waiting for deployment..."
          sleep 45

          echo "Getting application logs..."
          az webapp log show --name powerop-app --resource-group powerop-ml-rg --query application

          echo "Getting container logs..."
          az webapp log tail --name powerop-app --resource-group powerop-ml-rg
