name: Azure FastAPI Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Create deployment package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          zip -r deployment.zip . -x "*.git*"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App
        run: |
          # Stop the web app
          az webapp stop --name powerop-app --resource-group powerop-ml-rg

          # Configure settings
          az webapp config set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --linux-fx-version "PYTHON|3.9" \
            --startup-file "startup.sh"

          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              PYTHON_VERSION=3.9 \
              PORT=8000

          # Start the web app
          az webapp start --name powerop-app --resource-group powerop-ml-rg

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: powerop-app
          package: ./deployment.zip

      - name: Check deployment logs
        if: always()
        run: |
          sleep 30
          az webapp log download --name powerop-app --resource-group powerop-ml-rg
          echo "Latest logs:"
          az webapp log tail --name powerop-app --resource-group powerop-ml-rg
