name: Azure FastAPI Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Create deployment package
        run: |
          echo "=== Verifying files before packaging ==="
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

          echo "=== Creating deployment directory ==="
          mkdir -p deploy

          echo "=== Copying files ==="
          # Essential files
          cp -v startup.sh deploy/
          cp -v requirements.txt deploy/
          cp -v gunicorn_config.py deploy/
          cp -v runtime.txt deploy/
          cp -v .deployment deploy/

          echo "=== Copying API directory ==="
          cp -rv api deploy/

          echo "=== Verifying deployment directory ==="
          echo "Deployment directory contents:"
          ls -la deploy/
          echo "API directory contents:"
          ls -la deploy/api/

          echo "=== Creating ZIP archive ==="
          cd deploy
          zip -r ../deploy.zip .
          cd ..

          echo "=== Final package verification ==="
          echo "ZIP file size: $(ls -lh deploy.zip)"
          echo "ZIP contents:"
          unzip -l deploy.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App
        run: |
          echo "=== Configuring Python runtime ==="
          az webapp config set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --linux-fx-version "PYTHON|3.9" || true

          echo "=== Setting basic app settings ==="
          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              WEBSITES_PORT=8000 \
              PYTHON_VERSION=3.9 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              PYTHONPATH="/home/site/wwwroot" \
              PATH="/usr/local/bin:/usr/bin:/bin:/home/site/wwwroot/.local/bin" || true

          echo "=== Setting deployment and startup settings ==="
          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              WEBSITE_RUN_FROM_PACKAGE=1 \
              STARTUP_COMMAND="/home/site/wwwroot/.local/bin/gunicorn --chdir /home/site/wwwroot -c gunicorn_config.py api.main:app" || true

          echo "=== Setting logging settings ==="
          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              WEBSITE_HTTPLOGGING_RETENTION_DAYS=1 \
              DIAGNOSTICS_AZUREBLOBCONTAINERSASURL="" \
              DIAGNOSTICS_AZUREBLOBRETENTIONINDAYS=7 || true

          echo "=== Verifying configuration ==="
          az webapp config show --name powerop-app --resource-group powerop-ml-rg --query linuxFxVersion -o tsv

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: powerop-app
          package: deploy.zip

      - name: Deployment verification
        if: steps.deploy.outcome == 'success'
        run: |
          echo "=== Waiting for deployment to stabilize ==="
          sleep 30

          echo "=== Restarting web app ==="
          az webapp restart --name powerop-app --resource-group powerop-ml-rg
          sleep 90  # Wait after restart

          echo "=== Checking web app status ==="
          STATUS=$(az webapp show --name powerop-app --resource-group powerop-ml-rg --query state -o tsv)
          echo "Web app status: $STATUS"

          if [ "$STATUS" != "Running" ]; then
            echo "Web app is not in Running state"
            az webapp log deployment show --name powerop-app --resource-group powerop-ml-rg
            exit 1
          fi

          echo "=== Checking application logs ==="
          # Enable logging
          az webapp log config --name powerop-app --resource-group powerop-ml-rg --web-server-logging filesystem

          # Download logs
          az webapp log download --name powerop-app --resource-group powerop-ml-rg --log-file logs.zip
          unzip -o logs.zip
          cat LogFiles/application/*.log || true

          echo "=== Testing application health endpoint ==="
          WEBAPP_URL=$(az webapp show --name powerop-app --resource-group powerop-ml-rg --query defaultHostName -o tsv)
          MAX_RETRIES=8
          RETRY_COUNT=0
          WAIT_TIME=30

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Attempt $((RETRY_COUNT+1))/$MAX_RETRIES"
            
            # Get latest deployment logs
            az webapp log deployment show --name powerop-app --resource-group powerop-ml-rg

            # Try the health check
            RESPONSE=$(curl -s -w "\n%{http_code}" "https://$WEBAPP_URL/health")
            HTTP_BODY=$(echo "$RESPONSE" | head -n 1)
            HTTP_STATUS=$(echo "$RESPONSE" | tail -n 1)
            
            echo "Response body: $HTTP_BODY"
            echo "Status code: $HTTP_STATUS"

            if [ "$HTTP_STATUS" = "200" ]; then
              echo "Health check successful!"
              exit 0
            fi

            # Download and show latest logs
            az webapp log download --name powerop-app --resource-group powerop-ml-rg --log-file logs.zip
            unzip -o logs.zip
            echo "=== Latest application logs ==="
            cat LogFiles/application/*.log || true

            echo "Waiting ${WAIT_TIME} seconds before next attempt..."
            sleep $WAIT_TIME
            RETRY_COUNT=$((RETRY_COUNT+1))
            WAIT_TIME=$((WAIT_TIME + 15))
          done

          echo "=== Deployment failed - Final logs ==="
          az webapp log deployment show --name powerop-app --resource-group powerop-ml-rg
          cat LogFiles/application/*.log || true
          exit 1
