name: Azure FastAPI Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Create deployment package
        run: |
          echo "=== Verifying files before packaging ==="
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

          echo "=== Creating deployment directory ==="
          mkdir -p deploy

          echo "=== Copying files ==="
          # Essential files
          cp -v startup.sh deploy/
          cp -v requirements.txt deploy/
          cp -v gunicorn_config.py deploy/
          cp -v runtime.txt deploy/
          cp -v .deployment deploy/

          echo "=== Copying API directory ==="
          cp -rv api deploy/

          echo "=== Verifying deployment directory ==="
          echo "Deployment directory contents:"
          ls -la deploy/
          echo "API directory contents:"
          ls -la deploy/api/

          echo "=== Creating ZIP archive ==="
          cd deploy
          zip -r ../deploy.zip .
          cd ..

          echo "=== Final package verification ==="
          echo "ZIP file size: $(ls -lh deploy.zip)"
          echo "ZIP contents:"
          unzip -l deploy.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App
        run: |
          # Update Python configuration
          az webapp config set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --linux-fx-version "PYTHON|3.9"

          # Configure app settings
          az webapp config appsettings set \
            --name powerop-app \
            --resource-group powerop-ml-rg \
            --settings \
              WEBSITES_PORT=8000 \
              PYTHON_VERSION=3.9 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              WEBSITE_RUN_FROM_PACKAGE=1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: powerop-app
          package: deploy.zip
          clean: true
          restart: true

      - name: Deployment verification
        run: |
          echo "=== Waiting for deployment ==="
          sleep 30

          echo "=== Checking deployment status ==="
          DEPLOYMENT_STATUS=$(az webapp deployment list --name powerop-app --resource-group powerop-ml-rg --query "[0].status" -o tsv)
          echo "Deployment status: $DEPLOYMENT_STATUS"

          echo "=== Checking application logs ==="
          az webapp log tail --name powerop-app --resource-group powerop-ml-rg

          echo "=== Testing application ==="
          WEBAPP_URL=$(az webapp show --name powerop-app --resource-group powerop-ml-rg --query defaultHostName -o tsv)
          curl -v "https://$WEBAPP_URL/health" || true
